BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Config] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [CfgKey] VARCHAR(255) NOT NULL,
    [CfgValue] VARCHAR(255) NOT NULL,
    [Description] VARCHAR(500),
    CONSTRAINT [PK__Config__3214EC07BF1ADB93] PRIMARY KEY CLUSTERED ([Id])
);

-- CreateTable
CREATE TABLE [dbo].[TelegramWhitelist] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [ChatId] VARCHAR(255) NOT NULL,
    [AddedDate] DATETIME NOT NULL CONSTRAINT [DF__TelegramW__Added__628FA481] DEFAULT CURRENT_TIMESTAMP,
    [Remarks] VARCHAR(500),
    CONSTRAINT [PK__Telegram__3214EC07E40C6C08] PRIMARY KEY CLUSTERED ([Id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
